# Generated by Django 5.0.1 on 2024-01-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Choose',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Courses',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
